export const MARKETING_TEMPLATES = { spotlight: { label: "Produto em destaque", emoji: "⭐", headline: "DESTAQUE DA LOJA!" }, promo: { label: "Oferta especial", emoji: "🏷️", headline: "OFERTA IMPERDÍVEL!" }, last: { label: "Últimas unidades", emoji: "🚨", headline: "CORRE QUE ESTÁ ACABANDO!" }, new: { label: "Lançamento", emoji: "✨", headline: "NOVIDADE CHEGANDO!" }, bestseller: { label: "Mais vendido", emoji: "🏆", headline: "O QUERIDINHO DAS CLIENTES!" }, kit: { label: "Kit promocional", emoji: "🎁", headline: "MONTE SEU KIT ESPECIAL!" }, catalog: { label: "Compre pelo catálogo", emoji: "🛒", headline: "PEÇA PELO CATÁLOGO ONLINE!" }, whatsapp: { label: "Chame no WhatsApp", emoji: "💬", headline: "ME CHAMA NO WHATSAPP!" }, delivery: { label: "Frete/entrega", emoji: "🚚", headline: "ENTREGA COMBINADA!" }, preorder: { label: "Encomendas abertas", emoji: "📦", headline: "ENCOMENDAS ABERTAS!" } } as const;
export type MarketingTemplateId = keyof typeof MARKETING_TEMPLATES;
export const MARKETING_AD_THEMES = { brand: { label: "Marca da loja", accent: "#ec4899" }, purple: { label: "Roxo premium", accent: "#6d5dfc" }, blue: { label: "Azul catálogo", accent: "#2563eb" }, green: { label: "Verde vendas", accent: "#16a34a" }, rose: { label: "Rosa venda", accent: "#ec4899" }, orange: { label: "Laranja energia", accent: "#f97316" }, black: { label: "Escuro premium", accent: "#a78bfa" } } as const;
export type MarketingAdThemeId = keyof typeof MARKETING_AD_THEMES;
export const MARKETING_AD_THEME_IDS = Object.keys(MARKETING_AD_THEMES) as MarketingAdThemeId[];
export type MarketingBackgroundStyle = "soft-gradient" | "clean-card" | "dark-premium";
export interface MarketingAdTheme { id: MarketingAdThemeId; label: string; accent: string; dark: string; soft: string; surface: string; foreground: string; muted: string; ring: string; cta: string; background: string; darkMode: boolean; }
export interface MarketingAdConfig { productId: string; productName: string; productBrand?: string; productImageUrl?: string; imageUrl?: string; photoUrl?: string; image?: string; imageId?: string; productVolume?: string; stockStatus?: string; price: string | number; priceText: string; headline: string; note?: string; ctaText?: string; storeName: string; storeLogoUrl?: string; primaryColor: string; templateId: MarketingTemplateId; template?: MarketingTemplateId; themeId: MarketingAdThemeId; showBrand: boolean; showVolume: boolean; showStockStatus: boolean; showWhatsAppCta: boolean; backgroundStyle: MarketingBackgroundStyle; catalogUrl?: string; }
export type MarketingAdInput = Omit<Partial<MarketingAdConfig>, "template" | "templateId" | "themeId"> & { template?: string; templateId?: string; themeId?: string; brand?: string; salePrice?: string | number; productStock?: number; productExtras?: Record<string, unknown>; };
const MONEY_FORMATTER = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }), CONTROL_CHARS = /[\u0000-\u001F\u007F]/g;
export function sanitizeMarketingText(value: unknown, fallback = "", maxLength = 120) { const text = typeof value === "string" || typeof value === "number" ? String(value) : fallback; return text.replace(CONTROL_CHARS, " ").replace(/\s+/g, " ").trim().slice(0, maxLength) || fallback; }
export function parseMarketingPriceNumber(value: unknown) { if (typeof value === "number") return Number.isFinite(value) ? value : 0; const raw = sanitizeMarketingText(value, "0", 40).replace(/R\$|\s/g, ""), normalized = raw.includes(",") ? raw.replace(/\./g, "").replace(",", ".") : raw, numeric = Number.parseFloat(normalized.replace(/[^0-9.-]/g, "")); return Number.isFinite(numeric) ? numeric : 0; }
export function formatMarketingPrice(value: unknown) { return MONEY_FORMATTER.format(parseMarketingPriceNumber(value)).replace(/\u00a0/g, " "); }
export function resolveMarketingTemplate(value: unknown) { const key = sanitizeMarketingText(value, "promo", 40) as MarketingTemplateId; return MARKETING_TEMPLATES[key] ? { id: key, ...MARKETING_TEMPLATES[key] } : { id: "promo" as const, ...MARKETING_TEMPLATES.promo }; }
export function resolveMarketingAdTheme(value: unknown, fallbackColor?: string): MarketingAdTheme { const key = sanitizeMarketingText(value, "brand", 40) as MarketingAdThemeId, id = MARKETING_AD_THEMES[key] ? key : "brand", accent = id === "brand" ? fallbackColor || MARKETING_AD_THEMES.brand.accent : MARKETING_AD_THEMES[id].accent, darkMode = id === "black"; return { id, label: MARKETING_AD_THEMES[id].label, accent, dark: darkMode ? "#020617" : accent, soft: darkMode ? "#111827" : "#f8fafc", surface: darkMode ? "#0f172a" : "#ffffff", foreground: darkMode ? "#f8fafc" : "#111827", muted: darkMode ? "#cbd5e1" : "#64748b", ring: `${accent}38`, cta: id === "green" ? "#16a34a" : "#22c55e", background: darkMode ? "linear-gradient(135deg,#020617,#111827 52%,#312e81)" : `linear-gradient(135deg,#fff 0%,${accent}22 52%,#fff 100%)`, darkMode }; }
export function buildMarketingVolumeText(extras?: Record<string, unknown>) { if (!extras) return ""; for (const [key, label] of [["volume_ml", "Volume"], ["weight", "Peso"], ["size", "Tamanho"], ["quantity_pack", "Qtd."], ["flavor", "Sabor"], ["scent_family", "Fragrância"], ["model", "Modelo"], ["material", "Material"], ["color", "Cor"]]) { const value = sanitizeMarketingText(extras[key], "", 48); if (value) return `${label}: ${value}`; } return ""; }
export function buildMarketingStockLabel(stock?: number) { return typeof stock === "number" && Number.isFinite(stock) && stock <= 0 ? "Consulte disponibilidade" : "Pronta entrega"; }
export function buildMarketingAdConfig(input: MarketingAdInput): MarketingAdConfig { const template = resolveMarketingTemplate(input.templateId || input.template), primaryColor = sanitizeMarketingText(input.primaryColor, "#ec4899", 32), theme = resolveMarketingAdTheme(input.themeId, primaryColor), price = input.price ?? input.salePrice ?? 0, productVolume = sanitizeMarketingText(input.productVolume, "", 64) || buildMarketingVolumeText(input.productExtras); return { productId: sanitizeMarketingText(input.productId, "", 80), productName: sanitizeMarketingText(input.productName, "Produto", 120), productBrand: sanitizeMarketingText(input.productBrand || input.brand, "", 80), productImageUrl: sanitizeMarketingText(input.productImageUrl, "", 2048), imageUrl: sanitizeMarketingText(input.imageUrl, "", 2048), photoUrl: sanitizeMarketingText(input.photoUrl, "", 2048), image: sanitizeMarketingText(input.image, "", 2048), imageId: sanitizeMarketingText(input.imageId, "", 120), productVolume, stockStatus: sanitizeMarketingText(input.stockStatus, "", 60) || buildMarketingStockLabel(input.productStock), price, priceText: formatMarketingPrice(price), headline: sanitizeMarketingText(input.headline, template.headline, 80), note: sanitizeMarketingText(input.note, "", 80), ctaText: sanitizeMarketingText(input.ctaText, template.id === "catalog" ? "Confira nosso catálogo" : "Peça pelo WhatsApp", 80), storeName: sanitizeMarketingText(input.storeName, "Revenda Smart", 80), storeLogoUrl: sanitizeMarketingText(input.storeLogoUrl, "", 2048), primaryColor, templateId: template.id, template: template.id, themeId: theme.id, showBrand: input.showBrand !== false, showVolume: input.showVolume !== false, showStockStatus: input.showStockStatus !== false, showWhatsAppCta: input.showWhatsAppCta !== false, backgroundStyle: input.backgroundStyle || (theme.darkMode ? "dark-premium" : "soft-gradient"), catalogUrl: sanitizeMarketingText(input.catalogUrl, "", 2048) }; }
export function normalizeMarketingAdConfig(input: MarketingAdInput): MarketingAdConfig { return buildMarketingAdConfig(input); }
export function getMarketingAdImageCandidates(config: Pick<MarketingAdConfig, "productImageUrl" | "imageUrl" | "photoUrl" | "image">) { return [config.productImageUrl, config.imageUrl, config.photoUrl, config.image].filter((value): value is string => typeof value === "string" && value.trim().length > 0); }
export function hasBase64ImageValue(value: unknown) { return typeof value === "string" && /^data:image\//i.test(value.trim()); }
export function sanitizeMarketingHistoryPayload<T extends Record<string, unknown>>(entry: T): Partial<T> { const imageFields = new Set(["productImageUrl", "imageUrl", "photoUrl", "image", "storeLogoUrl"]); return Object.fromEntries(Object.entries(entry).filter(([key, value]) => value !== undefined && !(imageFields.has(key) && hasBase64ImageValue(value)))) as Partial<T>; }
export function buildMarketingAdMessage(config: MarketingAdConfig, payment?: { includePayment?: boolean; pixKey?: string; paymentLink?: string }) { const template = resolveMarketingTemplate(config.templateId), lines = [`${template.emoji} *${config.headline || template.headline}*`, "", `🛍️ *${config.productName}*`]; if (config.showBrand && config.productBrand) lines.push(`✨ Marca: ${config.productBrand}`); if (config.showVolume && config.productVolume) lines.push(`🔹 ${config.productVolume}`); lines.push(`💰 *Por apenas ${config.priceText}*`); if (config.showStockStatus && config.stockStatus) lines.push(`✅ ${config.stockStatus}`); if (config.note) lines.push(`📝 ${config.note}`); if (config.showWhatsAppCta && config.ctaText) lines.push("", `💬 ${config.ctaText}`); if (payment?.includePayment) { if (payment.pixKey) lines.push("", `🔑 PIX: ${payment.pixKey}`); if (payment.paymentLink) lines.push(`💳 Link de Pagamento: ${payment.paymentLink}`); } return lines.join("\n"); }
