import { expect, test } from "@playwright/test";
import { initializeFirebaseAdmin } from "../../server/firebase-admin-init";
import { buildOpportunityMessage, buildWhatsAppUrl } from "../../client/src/lib/opportunity-messages";

test("repeat purchase: real cadence, dashboard, WhatsApp/copy, explicit outcome and Free at 375px", async ({ page, context }) => {
  test.setTimeout(120_000);
  expect(process.env.FIRESTORE_EMULATOR_HOST).toBe("127.0.0.1:8080");
  process.env.FIREBASE_PROJECT_ID = "demo-revendasmart";
  const admin = initializeFirebaseAdmin(), db = admin.firestore();
  const email = `repeat-${Date.now()}@example.test`;
  const { uid } = await admin.auth().createUser({ email, password: "LocalTestPassword!123" });
  const owner = db.collection("users").doc(uid);
  const now = Date.now(), date = (days:number) => new Date(now-days*86400000).toISOString();
  await db.collection("user_settings").doc(uid).set({ userId:uid,storeName:"Loja Recompra QA",onboarding_completed:true,businessType:"products",businessTypes:["products"] });
  await owner.collection("planData").doc("main").set({currentPlan:"premium",premiumActive:true,premiumExpiresAt:null,premiumSource:"manual",premiumStartedAt:date(0)});
  await owner.collection("clients").doc("ana").set({id:"ana",name:"Ana Silva",phone:"",lastPurchaseAt:date(30)});
  await owner.collection("products").doc("creme").set({id:"creme",name:"Creme hidratante",stock:8,price:50,costPrice:20,lastSoldDate:date(30)});
  for (const days of [90,60,30]) await owner.collection("sales").doc(`sale-${days}`).set({id:`sale-${days}`,clientId:"ana",date:date(days),totalPrice:50,products:[{productId:"creme",quantity:1,price:50}]});
  const errors:string[]=[];
  page.on("pageerror",error=>errors.push(error.message));
  await page.addInitScript(()=>document.addEventListener("DOMContentLoaded",()=>{
    const style=document.createElement("style");style.textContent="vite-error-overlay {display:none!important}";document.head.append(style);
  }));
  await context.route("**/UserFeedbackToast.tsx", route => route.abort());
  await context.grantPermissions(["clipboard-read","clipboard-write"]);
  await context.route("https://wa.me/**",route=>route.fulfill({body:"Local URL verification",contentType:"text/plain"}));
  await page.setViewportSize({width:375,height:812});
  const responsePromise=page.waitForResponse(response=>response.url().endsWith("/api/opportunities")&&response.status()===200);
  await page.goto("/login");
  await page.getByRole("textbox",{name:"E-mail",exact:true}).fill(email);
  await page.locator('input[type="password"]').fill("LocalTestPassword!123");
  await page.getByRole("button",{name:"Entrar agora",exact:true}).click();
  const authoritative=(await (await responsePromise).json()).opportunities;
  const repeat=authoritative.find((item:{type:string})=>item.type==="repeat_purchase");
  expect(repeat).toBeTruthy();
  const dashboard=page.getByTestId("today-priorities");
  await expect(dashboard.getByTestId(`card-opportunity-${repeat.id}`)).toBeVisible();
  expect(await dashboard.locator('[data-testid^="card-opportunity-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute("data-testid"))))
    .toEqual(authoritative.slice(0,3).map((item:{id:string})=>`card-opportunity-${item.id}`));
  await page.screenshot({path:".tmp/repeat-dashboard-mobile.png",fullPage:true});
  await page.goto("/opportunities");
  const card=page.getByTestId(`card-opportunity-${repeat.id}`);
  await expect(card).toContainText("Ana Silva costuma comprar Creme hidratante aproximadamente a cada 30 dias.");
  await expect(card.getByRole("button",{name:"Abrir WhatsApp"})).toHaveCount(0);
  await card.getByRole("button",{name:"Ver cliente",exact:true}).click();
  await page.waitForURL(/\/clients\/ana/);
  const actions=owner.collection("opportunity_actions");
  expect((await actions.get()).size).toBe(0);
  await owner.collection("clients").doc("ana").update({phone:"11987654321"});
  await page.goto("/opportunities");
  await expect(card.getByRole("button",{name:"Abrir WhatsApp"})).toBeVisible();
  const popupPromise=page.waitForEvent("popup");
  await card.getByRole("button",{name:"Abrir WhatsApp"}).click();
  const popup=await popupPromise;await popup.waitForLoadState();
  expect(popup.url()).toBe(buildWhatsAppUrl("5511987654321",buildOpportunityMessage(repeat)!));
  await popup.close();
  expect((await actions.get()).size).toBe(0);
  await card.getByRole("button",{name:"Copiar",exact:true}).click();
  await expect(card.getByRole("button",{name:"Copiado!",exact:true})).toBeVisible();
  await expect(page.getByRole("status")).toContainText("Mensagem copiada.");
  expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(buildOpportunityMessage(repeat));
  expect((await actions.get()).size).toBe(0);
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:".tmp/repeat-card-mobile.png",fullPage:true});
  await card.getByRole("button",{name:"Marcar como feito"}).click();
  await expect(card).toHaveCount(0);
  await page.getByTestId("tab-opportunities-history").click();
  await expect(page.getByText("Feito — aguardando resultado",{exact:true})).toBeVisible();
  expect((await actions.doc(repeat.fingerprint).get()).data()!.outcome).toBeUndefined();
  await page.getByRole("button",{name:"Gerou resultado",exact:true}).click();
  await expect(page.getByText("Gerou resultado",{exact:true})).toBeVisible();
  await page.reload();
  await page.getByTestId("tab-opportunities-history").click();
  await expect(page.getByText("Gerou resultado",{exact:true})).toBeVisible();
  await page.screenshot({path:".tmp/repeat-history-mobile.png",fullPage:true});
  await owner.collection("planData").doc("main").set({currentPlan:"free",premiumActive:false,trialStatus:"expired",trialEndsAt:"2020-01-01T00:00:00.000Z"});
  const premiumRequests:string[]=[];
  page.on("request",request=>{if(request.url().includes("/api/opportunities"))premiumRequests.push(request.url());});
  await page.reload();
  await expect(page.getByTestId("button-opportunities-upgrade")).toBeVisible();
  await expect(page.getByText("Hora de recompra",{exact:true})).toHaveCount(0);
  await page.goto("/");
  await expect(page.getByTestId("button-dashboard-opportunities")).toBeVisible();
  await expect(dashboard).toHaveCount(0);
  expect(premiumRequests).toEqual([]);
  expect(errors.filter(error=>!/config-fetch-failed|API key not valid|analytics/i.test(error))).toEqual([]);
});
