import { expect, test } from "@playwright/test";
import { initializeFirebaseAdmin } from "../../server/firebase-admin-init";

test("stock risk: recent sell-through, dashboard, lifecycle, Free and 375px", async ({ page }) => {
  test.setTimeout(120_000);
  expect(process.env.FIRESTORE_EMULATOR_HOST).toBe("127.0.0.1:8080");
  process.env.FIREBASE_PROJECT_ID = "demo-revendasmart";
  const admin = initializeFirebaseAdmin();
  const db = admin.firestore();
  const email = `stock-risk-${Date.now()}@example.test`;
  const { uid } = await admin.auth().createUser({ email, password: "LocalTestPassword!123" });
  const owner = db.collection("users").doc(uid);
  const now = Date.now();
  const date = (days: number) => new Date(now - days * 86_400_000).toISOString();
  await db.collection("user_settings").doc(uid).set({ userId: uid, storeName: "Loja Estoque QA", onboarding_completed: true, businessType: "products", businessTypes: ["products"] });
  await owner.collection("planData").doc("main").set({ currentPlan: "premium", premiumActive: true, premiumExpiresAt: null, premiumSource: "manual", premiumStartedAt: date(0) });
  await owner.collection("products").doc("creme").set({ id: "creme", name: "Creme de alta saida", stock: 3, price: 20, costPrice: 8, lastSoldDate: date(1), tenantUid: uid });
  await owner.collection("sales").doc("sale-3").set({ id: "sale-3", clientId: "cliente", date: date(3), totalPrice: 120, products: [{ productId: "creme", quantity: 6, price: 20 }] });
  await owner.collection("sales").doc("sale-1").set({ id: "sale-1", clientId: "cliente", date: date(1), totalPrice: 120, products: [{ productId: "creme", quantity: 6, price: 20 }] });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.addInitScript(() => document.addEventListener("DOMContentLoaded", () => {
    const style = document.createElement("style"); style.textContent = "vite-error-overlay { display:none!important }"; document.head.append(style);
  }));
  await page.setViewportSize({ width: 375, height: 812 });
  let writes = 0;
  page.on("request", request => {
    if (request.url().includes("/api/opportunities") && request.method() !== "GET") writes++;
  });
  const responsePromise = page.waitForResponse(response => response.url().endsWith("/api/opportunities") && response.status() === 200);
  await page.goto("/login");
  await page.getByRole("textbox", { name: "E-mail", exact: true }).fill(email);
  await page.locator('input[type="password"]').fill("LocalTestPassword!123");
  await page.getByRole("button", { name: "Entrar agora", exact: true }).click();
  const authoritative = (await (await responsePromise).json()).opportunities;
  const risk = authoritative.find((item: { type: string }) => item.type === "stock_risk");
  expect(risk).toBeTruthy();
  expect(risk.priority).toBe("medium");
  expect(risk.reason).toContain("vendeu 12 unidade(s) nos últimos 30 dias");
  expect(risk.reason).toContain("aproximadamente 8 dia(s)");
  const dashboard = page.getByTestId("today-priorities");
  await expect(dashboard.getByTestId(`card-opportunity-${risk.id}`)).toBeVisible();
  expect(await dashboard.locator('[data-testid^="card-opportunity-"]').evaluateAll(elements => elements.map(element => element.getAttribute("data-testid"))))
    .toEqual(authoritative.slice(0, 3).map((item: { id: string }) => `card-opportunity-${item.id}`));
  expect(writes).toBe(0);
  await page.screenshot({ path: ".tmp/stock-risk-dashboard-mobile.png", fullPage: true });
  await page.goto("/opportunities");
  const card = page.getByTestId(`card-opportunity-${risk.id}`);
  await expect(card).toContainText("Risco de estoque");
  await expect(card).toContainText("Creme de alta saida vendeu 12 unidade(s) nos últimos 30 dias");
  await expect(card.getByRole("button", { name: "Repor estoque", exact: true })).toBeVisible();
  await expect(card.getByRole("button", { name: "Abrir WhatsApp" })).toHaveCount(0);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: ".tmp/stock-risk-card-mobile.png", fullPage: true });
  await card.getByRole("button", { name: "Repor estoque", exact: true }).click();
  await page.waitForURL(/\/edit-product\/creme/);
  expect((await owner.collection("opportunity_actions").get()).size).toBe(0);
  await page.goto("/opportunities");
  await card.getByRole("button", { name: "Marcar como feito" }).click();
  await expect(card).toHaveCount(0);
  await page.getByTestId("tab-opportunities-history").click();
  await expect(page.getByText("Feito — aguardando resultado", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Não gerou resultado", exact: true }).click();
  await expect(page.getByText("Não gerou resultado", { exact: true })).toBeVisible();
  await page.screenshot({ path: ".tmp/stock-risk-history-mobile.png", fullPage: true });
  await owner.collection("planData").doc("main").set({ currentPlan: "free", premiumActive: false, trialStatus: "expired", trialEndsAt: "2020-01-01T00:00:00.000Z" });
  const premiumRequests: string[] = [];
  page.on("request", request => { if (request.url().includes("/api/opportunities")) premiumRequests.push(request.url()); });
  await page.reload();
  await expect(page.getByTestId("button-opportunities-upgrade")).toBeVisible();
  await expect(page.getByText("Risco de estoque", { exact: true })).toHaveCount(0);
  await page.goto("/");
  await expect(page.getByTestId("button-dashboard-opportunities")).toBeVisible();
  await expect(dashboard).toHaveCount(0);
  expect(premiumRequests).toEqual([]);
  expect(errors.filter(error => !/config-fetch-failed|API key not valid|analytics/i.test(error))).toEqual([]);
});
